export { Loading } from './Loading/Loading'
export { Finish } from './FinishPage/FinishPage'
export { Fail } from './ErrorPage/ErrorPage'
export { Header } from './Header/Header'
export { Select } from './SelectButton/SelectButton'